version: "3.8"

services:
  amqc:
    image: ton_image_amqc:latest
    environment:
      - AMQC_HOST=0.0.0.0
      - AMQC_PORT=8180
      - ACTIVEMQ_HOST=amqc
      - ACTIVEMQ_PORT=8161
      - ACTIVEMQ_BROKER=localhost
      - ACTIVEMQ_USER=admin
      - ACTIVEMQ_PASS=admin
      - ACTIVEMQ_LOG_LEVEL=INFO
      - ACTIVEMQ_OPTS_MEMORY=-Xms128m -Xmx4096m
    volumes:
      - "/data/airng-data-global/activemq:/opt/activemq/data"
    ports:
      - 5672:5672
      - 61613:61613
      - 61614:61614
      - 61616:61616
    networks:
      - nyx_default
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    networks:
      - nyx_default
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
  nyx_default:
    external: true
